version: '3.8'

services:
  # --- BASE DE DATOS ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jose123 # Cámbiala por la tuya
      POSTGRES_DB: clinica_bolivia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- BACKEND ---
  backend:
    build: ./backend
    container_name: clinica_api
    ports:
      - "3000:3000"
    environment:
      # Aquí le decimos al backend que se conecte al servicio "db"
      DATABASE_URL: postgres://postgres:jose123123:5432/clinica_bolivia
      JWT_SECRET: CLAVE_SECRETA_SUPER_SEGURA
    depends_on:
      - db

  # --- FRONTEND ---
  frontend:
    build: ./frontend
    container_name: clinica_web
    ports:
      - "5173:5173"
    tty: true
    stdin_open: true # Necesario para Vite en Docker
    depends_on:
      - backend

# Volumen para que no se borren tus pacientes al apagar Docker
volumes:
  pgdata: